### PR TITLE
#23 Feature request: show description of service (and make it searchable)

### LINKED ISSUE #23: Feature request: show description of service (and make it searchable)
### Overview

The description could be very helpful to identify and find a service.

image

### Expected Behavior

Feature request:
- show description, I think as column
- enable searching in the description

### Actual Behavior

No description visible and can't search in it.

### Steps To Reproduce Behavior

Start the application. Search on a description.

--
### System Info

App Version: _v1.1
Operating System Version: Server 2012 R2

### PR DESCRIPTION
**Pull request by Jonatan-B**
## What Changed?

Added the the description into the DataGridView and allowed the filter utility to search on those fields as well. 

Its worth noting that the description field is not exposed by the GetServices() function, so it is a bit slower than before. Not much, but definitely noticeable. 

## Screenshots

image

## Issues Closed
#23

### CODE REVIEW

**Comment by BlythMeister** [comment]
@Jonatan-B your branch has conflicts, you need to rebase on the top of master.

**Comment by Jonatan-B** [comment]
I'll rebase my fork and re-add the changes. Then submit a new pull request.

**Comment by BlythMeister** [comment]
@Jonatan-B I've got some work I'm testing to help with background usage of wmi.
Using wmi on background refresh is really costly to CPU, I observed a spike of 10-20 percent every refresh.

You might want to wait for that so you can extend on top of that as description needs wmi

**Comment by Jonatan-B** [comment]
Cool, the way i implemented it wasn't so bad, especially because the filter didn't call Refresh every time, but I'll keep an eye out of that. 👍

**Comment by BlythMeister** [comment]
It's more the heartbeat background refresh which causes issues.
With the filter, quite like the way you implemented that, very clever 👍

I'll comment here when my performance changes are into master, and will wait for your pr before doing the next release 🙂

**Comment by Jonatan-B** [comment]
Awesome. Thank you! Looking forward to it.

**Comment by BlythMeister** [comment]
@Jonatan-B the performance changes are now in.
I also put the filtering logic from this PR is also added as i wanted to test something with it :)

**Pull request closed without merging**
