### PR TITLE
Add service install feature

### PR DESCRIPTION
**Pull request by UgurAldanmaz**
This feature has been proposed in [an issue](https://github.com/PaulStovell/ServiceBouncer/issues/4). @304NotModified found that it would be a 'killer' feature, so I developed it. :)
## New view of the main form

mainform
## Installation form

Do you have more than one service to install? Don't worry, more service can be installed one by one. Just select your first service exe then click the install. After installation complete, repeat installation steps for others.
installationform
## On close the installation form

If any service installed, they will be selected in the main form that they can be started easily by pressing the Start button.
afterinstallation

Thanks!

### CODE REVIEW

**Comment by 304NotModified** [comment]
Cool! Do you know if this will work with an executable with multiple services?

**Comment by UgurAldanmaz** [comment]
Thanks! 
I’m not sure that I understand. Could you explain by example?

**Comment by 304NotModified** [comment]
You can have multiple services in one project (=executable)

e.g.

``` c#
ServiceBase[] ServicesToRun;
ServicesToRun = new ServiceBase[]
                                {
                                    new Service1("Service1"),
                                    new Service2("Service2"),
                                    new Service3("Service3")
                                };

ServiceBase.Run(ServicesToRun);
```

**Comment by 304NotModified** [comment]
bump @PaulStovell

**Comment by 304NotModified** [comment]
works great @UgurAldanmaz !

**Comment by BlythMeister** [comment]
@UgurAldanmaz My merging another PR this now has conflicts.
Let me know when it's corrected and i will review 👍

**Comment by UgurAldanmaz** [comment]
Thank you @BlythMeister! I will correct it within this week.

**Comment by BlythMeister** [comment]
@UgurAldanmaz I've got a bit of a refactor going on, so you might want to hold fire, I'll let you know here when it's done.

**Comment by BlythMeister** [comment]
@UgurAldanmaz updates have been made
i've included an icon in the resource file for your install button :)

**Comment by UgurAldanmaz** [comment]
@BlythMeister , I made a new PR.

Thanks for the icon :)

**Comment by BlythMeister** [comment]
Other PR merged, closing this one

**Pull request closed without merging**
